server:
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
  port: 9003

spring:
    datasource:
        name: air
        url: jdbc:mysql://www.lifecat.club:3306/air
        username: root
        password: wangshihao
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapperLocations: classpath*:mapper/*.xml
    typeAliasesPackage: com.ten.air.back.entity