spring:
    datasource:
        name: air_server
        url: jdbc:mysql://localhost:3306/air_server
        username: root
        password: wangshihao
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapperLocations: classpath*:mapper/*.xml
    typeAliasesPackage: com.ten.air.back.entity